openapi: 3.0.3
info:
  title: Java API Requests and Responses Workshop - Core Criteria
  description: Core API for the Requests and Repsonses workshop
  version: 0.0.2

servers:
  - url: http://localhost:4000
tags:
  - name: publishers
paths:
  /publishers:
    post:
      tags:
        - publishers
      summary: Route to use (with a payload) when creating a new publisher
      description: New author creation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePublisher'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Publisher'
    get:
      tags:
        - publishers
      summary: Plain GET to access the whole list
      description: Get all of the listed publishers
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllPublisher'
  /publishers/{id}:
    get:
      tags:
        - publishers
      summary: Get a specific publisher using their ID
      description: Get one publisher from the list
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Publisher'
    put:
      tags:
        - publishers
      summary: Update an existing publisher
      description: use the ID of an publisher to update them using the payload
      parameters:
        - name: id
          in: path
          description: The ID of the publisher to update
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePublisher'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Publisher'
    delete:
      tags:
        - authors
      summary: Delete an author using the ID
      description: Delete an author using their ID
      parameters:
        - name: id
          in: path
          description: The ID of the author to delete
          required: true
          schema:
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Publisher'

components:
  schemas:
    CreatePublisher:
      type: object
      required: [name, city]
      properties:
        name:
          type: string
          example: "Houghton Mifflin Harcourt"
        city:
          type: string
          example: "Boston"
    Publisher:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Houghton Mifflin Harcourt"
        city:
          type: string
          example: "Boston"
    AllPublishers:
      type: array
      items:
        $ref: '#/components/schemas/Publisher'
